version: "3.9"

services:

  ####################################################
  # BunkerWeb Database
  ####################################################

  bw-db:
    image: mariadb:10.11
    container_name: bw-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: bunkerweb
      MYSQL_PASSWORD: bunkerweb

    volumes:
      - bw-db:/var/lib/mysql

    healthcheck:
      test: ["CMD","healthcheck.sh","--connect","--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - bunker


  ####################################################
  # BunkerWeb
  ####################################################

  bunkerweb:

    image: bunkerity/bunkerweb:1.6.12

    container_name: bunkerweb

    restart: unless-stopped

    depends_on:
      bw-db:
        condition: service_healthy

    environment:

      DATABASE_URI: "mariadb+pymysql://bunkerweb:bunkerweb@bw-db:3306/db"

      API_WHITELIST_IP: "127.0.0.0/8 172.16.0.0/12 192.168.0.0/16"

    ports:

      - "80:8080"
      - "443:8443"

    networks:
      - bunker
      - backend


  ####################################################
  # Scheduler
  ####################################################

  bw-scheduler:

    image: bunkerity/bunkerweb-scheduler:1.6.12

    container_name: bw-scheduler

    restart: unless-stopped

    depends_on:
      - bunkerweb

    environment:
      DATABASE_URI: "mariadb+pymysql://bunkerweb:bunkerweb@bw-db:3306/db"

      BUNKERWEB_INSTANCES: "bunkerweb"

      API_WHITELIST_IP: "127.0.0.0/8 172.16.0.0/12 192.168.0.0/16"

      UI_HOST: "http://bw-ui:7000"

      SERVER_NAME: "localhost"

      MULTISITE: "yes"

      localhost_USE_REVERSE_PROXY: "yes"
      localhost_REVERSE_PROXY_URL: "/"
      localhost_REVERSE_PROXY_HOST: "http://dvwa"

      localhost_USE_MODSECURITY: "yes"
      localhost_USE_MODSECURITY_CRS: "yes"

      localhost_USE_BAD_BEHAVIOR: "yes"

      localhost_USE_LIMIT_REQ: "yes"

      TZ: "Asia/Jakarta"

    volumes:

      - bw-storage:/data

    networks:
      - bunker
      - backend


  ####################################################
  # UI
  ####################################################

  bw-ui:

    image: bunkerity/bunkerweb-ui:1.6.12

    container_name: bw-ui

    restart: unless-stopped

    depends_on:
      - bw-db

    environment:

      DATABASE_URI: "mariadb+pymysql://bunkerweb:bunkerweb@bw-db:3306/db"

    ports:

      - "7000:7000"

    networks:
      - bunker


  ####################################################
  # DVWA
  ####################################################

  dvwa:

    image: ghcr.io/digininja/dvwa:latest

    container_name: dvwa

    restart: unless-stopped

    depends_on:
      dvwa-db:
        condition: service_healthy

    environment:

      DB_SERVER: dvwa-db
      DB_DATABASE: dvwa
      DB_USERNAME: dvwa
      DB_PASSWORD: password

    networks:
      - backend
      - dvwa-db


  ####################################################
  # DVWA Database
  ####################################################

  dvwa-db:

    image: mariadb:10.11

    container_name: dvwa-db

    restart: unless-stopped

    environment:

      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: password

    volumes:

      - dvwa-db:/var/lib/mysql

    healthcheck:

      test: ["CMD","healthcheck.sh","--connect","--innodb_initialized"]

      interval: 10s

      timeout: 5s

      retries: 5

    networks:
      - dvwa-db


####################################################
# NETWORKS
####################################################

networks:

  bunker:

  backend:

  dvwa-db:

    internal: true


####################################################
# VOLUMES
####################################################

volumes:

  bw-storage:

  bw-db:

  dvwa-db:
